#lang planet neil/sicp

; Mutex
(define (make-mutex)
  (let ((cell (list false)))
    (define (the-mutex m)
      (cond ((eq? m 'acquire)
             (if (test-and-set! cell)
                 (the-mutex 'acquire))) 
            ((eq? m 'release) (clear! cell))))
    the-mutex))
(define (clear! cell)
  (set-car! cell false))
(define (test-and-set! cell)
  (if (car cell)
      true
      (begin (set-car! cell true)
             false)))
; Serializer
(define (make-serializer)
  (let ((mutex (make-mutex)))
    (lambda (p)
      (define (serialized-p . args)
        (mutex 'acquire)
        (let ((val (apply p args)))
          (mutex 'release)
          val))
      serialized-p)))

; Exchange
(define (exchange account1 account2)
  (let ((difference (- (account1 'balance)
                       (account2 'balance))))
    ((account1 'withdraw) difference)
    ((account2 'deposit) difference)))

(define (serialized-exchange account1 account2)
  (let ((serializer1 (account1 'serializer))
        (serializer2 (account2 'serializer)))
    (if (< (account1 'acno) (account2 'acno))
        (begin (set! serializer1 (account2 'serializer))
               (set! serializer2 (account1 'serializer))))
    ((serializer1 (serializer2 exchange))
     account1
     account2)))

; Account number maker
(define (make-acno-maker)
  (let ((number 0))
    (define (next-number)
      (begin (set! number (+ number 1))
             number))
    (let ((acno-serializer (make-serializer)))
          (define (dispatch m)
            (cond ((eq? m 'number) (next-number)))))
    dispatch))

(define acno-maker (make-acno-maker))

; Account
(define (make-account-and-serializer balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((balance-serializer (make-serializer))
        (acno (acno-maker 'number)))
    (define (dispatch m)
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            ((eq? m 'balance) balance)
            ((eq? m 'acno) acno)
            ((eq? m 'serializer) balance-serializer)
            (else (error "Unknown request -- MAKE-ACCOUNT"
                         m))))
    dispatch))

; Test
(define acc1 (make-account-and-serializer 100))
(acc1 'acno)
(acc1 'balance)
(define acc2 (make-account-and-serializer 200))
(acc2 'acno)
(acc2 'balance)
(serialized-exchange acc1 acc2)
(acc1 'balance)
(acc2 'balance)
