#lang planet neil/sicp

;; 3.4

(define (make-account balance password)
  (let ((no-of-attempts 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (call-the-cops)
      "Cops called!")
    (define (wrong-password n)
      (if (>= no-of-attempts 7)
          (call-the-cops)
          (begin (set! no-of-attempts (+ no-of-attempts 1))
                 "Wrong Password!")))
    (define (dispatch pass m)
      (if (eq? pass password)
          (begin (set! no-of-attempts 0)
                 (cond ((eq? m 'withdraw) withdraw)
                       ((eq? m 'deposit) deposit)
                       (else (error "Unknown request -- MAKE-ACCOUNT"
                                    m))))
          wrong-password))
    dispatch))

(define AC1 (make-account 100 'a))
((AC1 'a 'withdraw) 20)
((AC1 'a 'deposit) 20)
((AC1 'b 'withdraw) 20)
((AC1 'b 'withdraw) 20)
((AC1 'b 'withdraw) 20)
((AC1 'b 'withdraw) 20)
((AC1 'b 'withdraw) 20)
((AC1 'b 'withdraw) 20)
((AC1 'b 'withdraw) 20)
;((AC1 'a 'deposit) 20)
((AC1 'b 'withdraw) 20)