#lang planet neil/sicp

;; 3.7

(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (check-password pass passwords)
    (if (list? passwords)
        (cond ((eq? (car passwords) pass) #t)
              ((null? passwords) #f)
              (else (check-password pass (cdr passwords))))
        (eq? pass passwords)))
  (define (add-password pass)
    (if (list? password)
        (set! password (append password pass))
        (set! password (list password pass))))
  (define (dispatch pass m)
    (if (check-password pass password)
         (cond ((eq? m 'withdraw) withdraw)
               ((eq? m 'deposit) deposit)
               ((eq? m 'add-password) add-password)
               (else (error "Unknown request -- MAKE-ACCOUNT"
                       m)))
         (error "Incorrect Password")))
  dispatch)

(define (make-joint account pass new-password)
  ((account pass 'add-password) new-password))

(define AC1 (make-account 100 'a))
((AC1 'a 'withdraw) 20)
((AC1 'a 'deposit) 20)
;(make-joint AC1 'a 'b)
((AC1 'b 'withdraw) 20)
